//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymSession
    {
        public int GymSessionsId { get; set; }
        public string SessionName { get; set; }
        public string SessionDay { get; set; }
        public string SessionHour { get; set; }
        public int SessionWeek { get; set; }
        public int RemainingSlots { get; set; }
    }
}
